# Generated by Django 4.2.6 on 2023-10-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='series/image')),
                ('video', models.FileField(upload_to='series/videos')),
                ('language', models.CharField(max_length=100)),
                ('rating_outof_10', models.IntegerField()),
                ('season', models.IntegerField()),
            ],
        ),
    ]
