# Generated by Django 4.2.4 on 2023-11-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_no_of_episodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scname', models.CharField(max_length=50)),
                ('simage', models.FileField(blank=True, null=True, upload_to='image/simage')),
            ],
        ),
    ]
