# Generated by Django 4.2.4 on 2023-11-29 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_scategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='series.scategory'),
        ),
    ]
