# Generated by Django 4.2.6 on 2023-10-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='movies/cover'),
        ),
    ]
