# Generated by Django 4.2.7 on 2023-12-06 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch', '0005_rename_subscribe_annual_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='annual',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='annual',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='freetrial',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='freetrial',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='month',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='month',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Freetriallist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
